### ISSUE TITLE
maven build failed

### ISSUE THREAD

**Issue by iyabchen** [pires/netty-tcnative-alpine#6]
Maven build failed on both Final 2.0.0 or master. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project netty-tcnative: Compilation failure -> [Help 1]

Is it because jdk version changed?

**Comment by pires** [comment]
Can you provide more logs?

**Comment by iyabchen** [comment]
Doing exactly the same as what README told:
1> git clone
2> docker build --build-arg NETTY_TCNATIVE_TAG=netty-tcnative-parent-2.0.0.Final -t pires/netty-tcnative-alpine:2.0.0.Final .
3> mkdir binaries
     docker run -v `pwd`/binaries:/output pires/netty-tcnative-alpine:2.0.0.Final

The following is the output:

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /netty-tcnative/openssl-dynamic/target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [ 23.712 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. FAILURE [  3.570 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. SKIPPED
[INFO] Netty/TomcatNative [BoringSSL - Static] ............ SKIPPED
[INFO] Netty/TomcatNative [LibreSSL - Static] ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.335 s
[INFO] Finished at: 2017-06-15T01:23:16+00:00
[INFO] Final Memory: 23M/783M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project netty-tcnative: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project netty-tcnative: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:862)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more

[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-tcnative
mv: can't rename 'openssl-dynamic/target/*.jar': No such file or directory
mv: can't rename 'openssl-static/target/*.jar': No such file or directory
mv: can't rename 'boringssl-static/target/*.jar': No such file or directory

**Comment by dylanscott** [comment]
I'm getting a similar error that seems to boil down to this error during the maven build:

```
[INFO] --- maven-antrun-plugin:1.8:run (build-openssl) @ netty-tcnative-openssl-static ---
[INFO] Executing tasks

main:
      [ftp] getting files
      [ftp] transferring old/1.0.2/openssl-1.0.2k.tar.gz to /netty-tcnative/openssl-static/target/old/1.0.2/openssl-1.0.2k.tar.gz
      [ftp] 1 files retrieved
     [exec] tar: can't open 'openssl-1.0.2k.tar.gz': No such file or directory
```

It seems like this may be an issue with the netty-tcnative project itself since it configures this maven build. I unfortunately don't know enough about maven to dig into it further.

EDIT: Note this build failure is in the `Netty/TomcatNative [OpenSSL - Static]` target, whereas OP's seems to be failing in `Netty/TomcatNative [OpenSSL - Dynamic]`

EDIT2: I was able to get this to work by using the `netty-tcnative-parent-2.0.3.Final` tag from the netty-tcnative repo instead of the 2.0.0 on in the README. For completeness those commands looked like:

```sh
docker build --build-arg NETTY_TCNATIVE_TAG=netty-tcnative-parent-2.0.3.Final -t pires/netty-tcnative-alpine:2.0.3.Final .
mkdir binaries
docker run -v `pwd`/binaries:/output pires/netty-tcnative-alpine:2.0.3.Final
```
